services:
  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379

  celery_worker:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./docker_env
    command: celery -A bg_upgrades worker -l info
    develop:
      watch:
        - action: sync+restart
          path: ./django_app
          target: /app
    volumes:
      - tmp_storage:/tmp
      - django_results:/app/tmp
    depends_on:
      - redis

  uwsgi:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      # - ./docker_env.prod
      - ./docker_env
    command: /bin/sh ./start_uwsgi.sh
    develop:
      watch:
        - action: sync+restart
          path: ./django_app
          target: /app
    volumes:
      - django_staticfiles:/app/staticfiles
      - socket:/sock
      - tmp_storage:/tmp
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      # dockerfile: ./Dockerfile.prod
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - django_staticfiles:/staticfiles
      - django_results:/result
      - socket:/sock
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  socket:
  django_staticfiles:
  django_results:
  tmp_storage: