version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    #env_file:
      #- ./.env/.dev-sample
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: celery
    command: celery -A bg_upgrades worker -l info
    #env_file:
      #- ./.env/.dev-sample
    depends_on:
      - redis
      - web

#volumes: