services:
  redis:
    image: redis:7-alpine

  celery_worker:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./docker_env
    command: celery -A bg_upgrades worker -l info
    develop:
      watch:
        - action: sync+restart
          path: ./django_app
          target: /app
    volumes:
      - tmp_storage:/tmp
      - django_results:/app/tmp
    depends_on:
      - redis

  uwsgi:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./docker_env
    command: /bin/sh ./start_uwsgi.sh
    develop:
      watch:
        - action: sync+restart
          path: ./django_app
          target: /app
    volumes:
      - django_staticfiles:/app/staticfiles
      - socket:/sock
      - tmp_storage:/tmp
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - django_staticfiles:/staticfiles
      - django_results:/result
      - socket:/sock
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
    depends_on:
      - redis
      - uwsgi
      - celery_worker
    ports:
      - 80:80
      - 443:443

volumes:
  socket:
  django_staticfiles:
  django_results:
  tmp_storage: